# Generated by Django 3.1.1 on 2020-09-28 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_no', models.IntegerField()),
                ('article_newspaper', models.CharField(max_length=200)),
                ('article_title', models.CharField(max_length=1000)),
                ('article_link', models.URLField()),
                ('article_image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Article_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_publish_date', models.DateField()),
                ('article_publish_time', models.TimeField()),
                ('article_modify_date', models.DateField()),
                ('article_modify_time', models.TimeField()),
                ('article_author', models.CharField(max_length=200)),
                ('article_category', models.CharField(max_length=200)),
                ('article_flex', models.CharField(max_length=200)),
                ('article_newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_newspaper', to='heari.article')),
                ('article_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_no', to='heari.article')),
            ],
        ),
    ]
